[functions]
  external_node_modules = ["express", "bcryptjs", "cors", "express-validator"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
